### ISSUE TITLE
Crash On Dedicated Server

### ISSUE THREAD

**Issue by InsomniaKitten** [MrIbby/EnderCompass#11]
Server crashes during startup.

**Mod version:** [1.2.5.1](https://minecraft.curseforge.com/projects/ender-compass/files/2347480)
**Forge version:** [1.11-13.19.1.2189](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11-13.19.1.2189/forge-1.11-13.19.1.2189-changelog.txt)

**Crash report:** [hastebin/ukikimukum](http://hastebin.com/ukikimukum.txt)

**Comment by Endmateria** [comment]
Sever crashes during startup.

Mod version 1.2.5.1
Forge version 1.11.2-13.20.0.2230 (newest)
Crash report: https://gist.github.com/Endmateria/ca8234d319f1a090640491488f828d58#file-crash-2017-02-14_20-51-16-server-txt

**Comment by ThomasAunvik** [comment]
Same thing happens to me:
http://pastebin.com/dD2RgYrM
Mod Version: 1.2.5.1
Forge Version: 13.20.0.2259
Java Version: 1.8.0_121

**Comment by MrIbby** [comment]
I'll look into it.

**Comment by MrIbby** [comment]
Try this: https://www.dropbox.com/s/bws809i4noqo3eh/EnderCompass-1.11-1.2.5.2-SNAPSHOT.jar?dl=0

**Comment by Endmateria** [comment]
I'm not running a server anymore, just singleplayer... but I was able to resolve this issue by only loading the mod client side.  When loaded both server and client side, that's when I'd get the crash.  So if that patch works for you ThomasAunvik, feel free to close the issue, since I'm not gonna set up my whole server again just to test it.

**Comment by ThomasAunvik** [comment]
1.2.5.2 Does not crash the server. Thank you!
